services:
  - type: web
    name: restaurant-dashboard
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MYSQL_HOST
        fromSecret: MYSQL_HOST
      - key: MYSQL_USER
        fromSecret: MYSQL_USER
      - key: MYSQL_PASSWORD
        fromSecret: MYSQL_PASSWORD
      - key: MYSQL_DATABASE
        fromSecret: MYSQL_DATABASE